# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fileorganizer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys
import os
import shutil


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(570, 217)
        MainWindow.setStyleSheet("background-color: rgb(211, 215, 207);\n"
"background-color: rgb(238, 238, 236);")
        self.setFixedSize(580, 220)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 561, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(31)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(480, 110, 89, 25))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton.setStyleSheet("QPushButton{border-top-rigth-radius:20px;background-color: rgb(138, 226, 52);}\n"
"QPushButton:hover{color: #fff; background-color: rgb(114, 159, 207)}\n"
"")
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(480, 190, 89, 25))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{border-top-rigth-radius:200px;background-color: rgb(138, 226, 52);}\n"
"QPushButton:hover{color: #fff; background-color: rgb(114, 159, 207)}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 190, 89, 25))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{border-top-rigth-radius:20px;background-color: rgb(138, 226, 52);}\n"
"QPushButton:hover{color: #fff; background-color: rgb(114, 159, 207)}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 110, 201, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(480, 140, 89, 31))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton{border-top-rigth-radius:15px;}\n"
"QPushButton:hover{color: #fff; background-color: rgb(114, 159, 207)}\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python Organizer"))
        self.label_2.setText(_translate("MainWindow", "100% Python File Organizer!"))
        self.pushButton.setText(_translate("MainWindow", "Clean Up!"))

        self.pushButton_2.setText(_translate("MainWindow", "Créditos"))
        self.pushButton_2.clicked.connect(Workers.Creditos)

        self.pushButton_3.setText(_translate("MainWindow", "Donate!"))
        self.pushButton_3.clicked.connect(Workers.Donate)

        
        self.label.setText(_translate("MainWindow", "Select the folder:"))
        
        self.pushButton_4.setText(_translate("MainWindow", "Path"))
        self.pushButton_4.clicked.connect(Workers.openFiles)
        self.pushButton.clicked.connect(Workers.Organizer)

        

class Workers():
        def openFiles(self):
        
        
                openFile = QtWidgets.QFileDialog.getExistingDirectory(None, 'Select', '/')
                global file
                file= openFile


                print(file)

        def Organizer():
                dir = file
                files_organizer = os.listdir(dir)

                for x in files_organizer:
                        type = os.path.splitext(x)
                        newtype =  str(type [1:])
                        
                        print(newtype)
                
                        if os.path.exists(dir+'/'+newtype):
                                shutil.move(dir+'/'+x, dir+'/'+newtype)

                        else: 
                                os.mkdir(dir+'/'+newtype)
                                shutil.move(dir+'/'+x, dir+'/'+newtype)
                                print('is done! ;)')
        

                response = QMessageBox()
                response.setText("All successfully organized!")
                response.exec_()
        

        def Creditos():
                response = QMessageBox()
                response.setText("Pedro Larrieu")
                response.exec_()
        
        def Donate():
                response = QMessageBox()
                response.setText("pix: pedrolarrieu@gmail.com")
                response.exec_()
